#include "../Fjord.h"

void Polygon::Render() {
    //printf("Made it here\n");
    _rotate_points();
    std::vector<float>* vertexes = shape.GetGLPointArray(transform.global_position);
    RenderCall rc = {RenderCall::POLYGON, vertexes};
    engine.back_buffer.push_back(rc);
}

void Polygon::_rotate_points(){
    for (Vector2 point : shape.shape){
        float radians = transform.global_rotation * (M_PI / 180.0f); // Convert degrees to radians
        // Generated by CoPilot cuz i dont feel like typing it out lol
        float x_rotated = point.x * cos(radians) - point.y * sin(radians);
        float y_rotated = point.x * sin(radians) + point.y * cos(radians);
        point.x = parent->transform.global_position.x + x_rotated;
        transform.global_position.y = parent->transform.global_position.y + y_rotated;
    }
}